### ISSUE TITLE
Using Curl on Custom Domain with ip-lookup

### ISSUE THREAD

**Issue by jiriteach** [amodm/ip-lookup#3]
Hi - I have a question on using curl with a custom domain with ip-lookup.

If I simply run curl xx.domain.xx I get a blank response. If I run curl xx.xx.workers.dev - I get a response of the IP.
Any reason why this might be the case?

Thanks

**Comment by amodm** [comment]
Have you configured the appropriate [worker route](https://developers.cloudflare.com/workers/platform/routing/routes/)? You can do it via the dashboard, or inside your [wrangler.toml](https://developers.cloudflare.com/workers/wrangler/configuration/)

**Comment by jiriteach** [comment]
> Have you configured the appropriate [worker route](https://developers.cloudflare.com/workers/platform/routing/routes/)? You can do it via the dashboard, or inside your [wrangler.toml](https://developers.cloudflare.com/workers/wrangler/configuration/)

Yup I have and tried various combinations but no luck. I noticed the same issue with your custom domain - ip.rootnet.in

If you curl ip.rootnet.in - there is a blank response which makes me wonder if it's logic related.

**Comment by amodm** [comment]
> If you curl ip.rootnet.in - there is a blank response which makes me wonder if it's logic related.

What do you mean? I see responses perfectly fine for `ip.rootnet.in` (tested from multiple locations)

**Comment by jiriteach** [comment]
> > If you curl ip.rootnet.in - there is a blank response which makes me wonder if it's logic related.
> 
> What do you mean? I see responses perfectly fine for `ip.rootnet.in` (tested from multiple locations)

See this example - 

<img width="503" alt="Screen Shot 2022-07-04 at 19 18 41" src="https://user-images.githubusercontent.com/2116446/177102610-24c913fc-65b4-43f7-bf99-6f41a5226ca1.png">

Am deliberately not using https://

**Comment by amodm** [comment]
Can you please share the output of `curl -v https://ip.rootnet.in`?

**Comment by jiriteach** [comment]
> Can you please share the output of `curl -v https://ip.rootnet.in`?

Sure

```
jxs@WHEELIE ~ % curl -v https://ip.rootnet.in
*   Trying 172.66.43.150:443...
* Connected to ip.rootnet.in (172.66.43.150) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* (304) (OUT), TLS handshake, Client hello (1):
* (304) (IN), TLS handshake, Server hello (2):
* (304) (IN), TLS handshake, Unknown (8):
* (304) (IN), TLS handshake, Certificate (11):
* (304) (IN), TLS handshake, CERT verify (15):
* (304) (IN), TLS handshake, Finished (20):
* (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-CHACHA20-POLY1305-SHA256
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: May 17 00:00:00 2022 GMT
*  expire date: May 17 23:59:59 2023 GMT
*  subjectAltName: host "ip.rootnet.in" matched cert's "*.rootnet.in"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x15c00d400)
> GET / HTTP/2
> Host: ip.rootnet.in
> user-agent: curl/7.79.1
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 256)!
< HTTP/2 200 
< date: Mon, 04 Jul 2022 07:47:59 GMT
< content-type: text/plain;charset=utf-8
< content-length: 15
< cache-control: no-cache
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=es0xTaSFlSTHCQOEn0xiJbxSmA%2BKqyvkzbjlYHLhyWRbkkpYxp18zlDP4T0K%2FdhyKYg%2FXCAwffCPf3K2V19ak5NRIUpE2OwWhha%2FN5s%2BUFKGYPMT7eWX5cRLH76ZYGE%3D"}],"group":"cf-nel","max_age":604800}
< nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
< strict-transport-security: max-age=0; includeSubDomains; preload
< x-content-type-options: nosniff
< server: cloudflare
< cf-ray: 725641892d8ea42d-AKL
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
< 
121.99.xx.xx
* Connection #0 to host ip.rootnet.in left intact
```
Have masked the response IP.

**Comment by amodm** [comment]
As can be seen here, you **are** receiving the IP. I don't know why your local `curl` isn't showing the output without the `-v` option, but I'm unable to replicate this. If you can share some data that shows something wrong with the service, I can act on it, else I'll treat this as a non-issue in the next 24 hrs.

As to why your own hosted service isn't working, it strongly seems to be a route configuration issue. Can you share your `wrangler.toml` (masking out any private data), or share a screenshot of the service dashboard's `Triggers` section?

**Comment by jiriteach** [comment]
Thanks for looking into this.
So this is my analysis of the following scenarios with explation to make things a little clearer - 

```
curl https://ip.rootnet.in <-- WORKS
curl http://ip.rootnet.in <-- DOES NOT WORK. Note no HTTPS

curl ip.rootnet.in <-- DOES NOT WORK. Note no HTTP or HTTPS

curl https://defaultworkerurl <-- WORKS
curl http://defaultworkerurl <-- WORKS. Note no HTTPS

curl defaultworkerurl <-- WORKS. Note no HTTP or HTTPS
```

So - I am trying to determine if this is the code or Cloudflare Workers configuration. Not sure why the defaultworkerurl is working but custom domains is not for these scenarios.

**Comment by amodm** [comment]
Ah, http calls get redirected to https. You'll need to use `curl -L` for 301 redirects to work, as curl doesn't follow redirects automatically.

**Comment by jiriteach** [comment]
> Ah, http calls get redirected to https. You'll need to use `curl -L` for 301 redirects to work, as curl doesn't follow redirects automatically.

Thanks. That does work using -L.
Makes me think that its more a Cloudflare implementation issue as curl -L is not required for the defaultworkerurl.

It seems that custom domains for Cloudflare workers respond of HTTP and redirect to HTTPS. Good to know its not the code. Thanks.
